com:
  gci:
    junit5:
      kafka:
        bootstrap.servers: ${spring.embedded.kafka.brokers}
        topic: test
      mongo:
        host: localhost
        port: 123 # To be populated by RandomPortInitializer.
        database: testdb
      activemq:
        brokerurl: vm://embedded-broker?create=false
        queuename: testqueue
      mysql:
        port: 123 # To be populated by RandomPortInitializer.
        schema: testschema
        domain: localhost
        username: auser
        password: sa
spring:
  datasource:
    url: jdbc:mysql://${com.gci.junit5.mysql.domain}:${com.gci.junit5.mysql.port}/${com.gci.junit5.mysql.schema}
    username: ${com.gci.junit5.mysql.username}
    password: ${com.gci.junit5.mysql.password}
  jpa:
    hibernate:
      ddl-auto: create # Should only be 'create' for unit tests.  Otherwise, this will rewrite your db.
